### ISSUE TITLE
No module named pyowm

### ISSUE THREAD

**Issue by Tr33x0rs** [LennyHirsch/UnicornHatHD-Weather-Clock#1]
I followed your instructions although I think that i'm still having issues with pyowm. When running "sudo python weatherclock.py" I receive an error saying "ImportError: No module named pyowm".

I tried using sudo pip3 install pyowm which comes up and says "Requirement already satisfied" although it isn't running. Any help is greatly appreciated. Thank you in advance.

**Comment by rob-bru** [comment]
Try:

sudo pip install pyowm
sudo pip install pytz
